#ServerMOTD
joined-before:
  - "&6Hello, &2%player%!"
  - "&6You can have multiple MOTDs here! They will be randomised!"
never-joined:
  - "&bI see you have not joined before!"
  - "&dChange me in config.yml!"
not-whitelisted:
  - "&c&lYou aren't whitelisted. Sorry! "
banned: 
  - "&c&lYou have been &nbanned&r&c&l"